# Generated by Django 4.2.1 on 2023-05-24 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('style_nr', models.IntegerField(unique=True)),
                ('style_catalog_page', models.IntegerField()),
                ('supplier_code', models.CharField(max_length=20)),
                ('supplier_article_code', models.CharField(max_length=20)),
                ('brand_code', models.CharField(max_length=20)),
                ('brand_name', models.CharField(max_length=20)),
                ('style_name', models.CharField(max_length=255)),
                ('style_description', models.TextField()),
                ('style_category_main', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Filter_Group',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('filter_group', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('sku_artnum', models.IntegerField()),
                ('sku_color_code', models.CharField(max_length=20)),
                ('sku_color_name', models.CharField(max_length=50)),
                ('sku_color_swatch', models.CharField(max_length=100)),
                ('sku_color_swatch_url', models.CharField(max_length=250)),
                ('sku_color_swatch_local', models.CharField(max_length=100)),
                ('sku_color_picture', models.CharField(max_length=100)),
                ('sku_color_picture_url', models.CharField(max_length=250)),
                ('sku_color_picture_local', models.CharField(max_length=100)),
                ('sku_size_code', models.CharField(max_length=50)),
                ('sku_size_name', models.CharField(max_length=50)),
                ('sku_size_order', models.IntegerField()),
                ('sku_changed_date', models.CharField(max_length=50)),
                ('sku_closeout', models.CharField(max_length=50)),
                ('sku_new', models.CharField(max_length=50)),
                ('sku_ean', models.CharField(max_length=50)),
                ('sku_weight', models.CharField(max_length=50)),
                ('sku_coo', models.CharField(max_length=50)),
                ('sku_pieces_in_pack', models.IntegerField()),
                ('sku_pieces_in_carton', models.IntegerField()),
                ('price_currency', models.CharField(max_length=50)),
                ('price_exchange_rate', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_g', models.IntegerField()),
                ('stock_y', models.IntegerField()),
                ('stock_b', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Subcategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('category_name', models.CharField(max_length=250)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Picture',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('filename', models.CharField(max_length=250)),
                ('pos', models.IntegerField()),
                ('url', models.CharField(max_length=250)),
                ('local_url', models.CharField(max_length=250)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Filter',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('filter_content', models.CharField(max_length=250)),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product_filter_group')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product')),
            ],
        ),
    ]
